/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { CalendarEventService } from "../calendarEvent.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { CalendarEventCreateInput } from "./CalendarEventCreateInput";
import { CalendarEvent } from "./CalendarEvent";
import { CalendarEventFindManyArgs } from "./CalendarEventFindManyArgs";
import { CalendarEventWhereUniqueInput } from "./CalendarEventWhereUniqueInput";
import { CalendarEventUpdateInput } from "./CalendarEventUpdateInput";
import { AppointmentFindManyArgs } from "../../appointment/base/AppointmentFindManyArgs";
import { Appointment } from "../../appointment/base/Appointment";
import { AppointmentWhereUniqueInput } from "../../appointment/base/AppointmentWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class CalendarEventControllerBase {
  constructor(
    protected readonly service: CalendarEventService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: CalendarEvent })
  @nestAccessControl.UseRoles({
    resource: "CalendarEvent",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: CalendarEventCreateInput,
  })
  async createCalendarEvent(
    @common.Body() data: CalendarEventCreateInput
  ): Promise<CalendarEvent> {
    return await this.service.createCalendarEvent({
      data: data,
      select: {
        createdAt: true,
        eventDate: true,
        eventName: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [CalendarEvent] })
  @ApiNestedQuery(CalendarEventFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "CalendarEvent",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async calendarEvents(
    @common.Req() request: Request
  ): Promise<CalendarEvent[]> {
    const args = plainToClass(CalendarEventFindManyArgs, request.query);
    return this.service.calendarEvents({
      ...args,
      select: {
        createdAt: true,
        eventDate: true,
        eventName: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: CalendarEvent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CalendarEvent",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async calendarEvent(
    @common.Param() params: CalendarEventWhereUniqueInput
  ): Promise<CalendarEvent | null> {
    const result = await this.service.calendarEvent({
      where: params,
      select: {
        createdAt: true,
        eventDate: true,
        eventName: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: CalendarEvent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CalendarEvent",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: CalendarEventUpdateInput,
  })
  async updateCalendarEvent(
    @common.Param() params: CalendarEventWhereUniqueInput,
    @common.Body() data: CalendarEventUpdateInput
  ): Promise<CalendarEvent | null> {
    try {
      return await this.service.updateCalendarEvent({
        where: params,
        data: data,
        select: {
          createdAt: true,
          eventDate: true,
          eventName: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: CalendarEvent })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "CalendarEvent",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteCalendarEvent(
    @common.Param() params: CalendarEventWhereUniqueInput
  ): Promise<CalendarEvent | null> {
    try {
      return await this.service.deleteCalendarEvent({
        where: params,
        select: {
          createdAt: true,
          eventDate: true,
          eventName: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/appointments")
  @ApiNestedQuery(AppointmentFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Appointment",
    action: "read",
    possession: "any",
  })
  async findAppointments(
    @common.Req() request: Request,
    @common.Param() params: CalendarEventWhereUniqueInput
  ): Promise<Appointment[]> {
    const query = plainToClass(AppointmentFindManyArgs, request.query);
    const results = await this.service.findAppointments(params.id, {
      ...query,
      select: {
        appointmentDate: true,

        calendarEvent: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/appointments")
  @nestAccessControl.UseRoles({
    resource: "CalendarEvent",
    action: "update",
    possession: "any",
  })
  async connectAppointments(
    @common.Param() params: CalendarEventWhereUniqueInput,
    @common.Body() body: AppointmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      appointments: {
        connect: body,
      },
    };
    await this.service.updateCalendarEvent({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/appointments")
  @nestAccessControl.UseRoles({
    resource: "CalendarEvent",
    action: "update",
    possession: "any",
  })
  async updateAppointments(
    @common.Param() params: CalendarEventWhereUniqueInput,
    @common.Body() body: AppointmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      appointments: {
        set: body,
      },
    };
    await this.service.updateCalendarEvent({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/appointments")
  @nestAccessControl.UseRoles({
    resource: "CalendarEvent",
    action: "update",
    possession: "any",
  })
  async disconnectAppointments(
    @common.Param() params: CalendarEventWhereUniqueInput,
    @common.Body() body: AppointmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      appointments: {
        disconnect: body,
      },
    };
    await this.service.updateCalendarEvent({
      where: params,
      data,
      select: { id: true },
    });
  }
}
